baseURL = 'https://alexandra.magin.org/'
languageCode = 'en-US'
title = 'Alexandra Magin'
author = 'Alexandra Magin'

enableRobotsTXT = true

theme = 'hugo-bearblog'

[params]
  description = 'Alexandra Magin'
  # favicon = "static/favicon.ico"
  title = 'Alexandra Magin'

  dateFormat = '2006-01-02'
  math = false

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
